version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - go-app
